baseURL = 'https://cpnet2.gil-web.com/'
languageCode = 'fr-fr'
title = 'Copronet'
theme = 'copronet'
pagination.pagerSize = 2

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
name = "Nous conna√Ætre"
url = "/nous-connaitre"
weight = 10

[[menu.main]]
name = "Nos Services"
url = "/nos-services"
weight = 20

[[menu.main]]
name = "Notre Offre"
url = "/notre-offre"
weight = 30

[[menu.main]]
name = "Nous Contacter"
url = "/nous-contacter"
weight = 40

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 50

[taxonomies]
tag = "tags"
category = "categories"
